name: PR Review Check

on:
  issue_comment:
    types: [created]

jobs:
  check-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR review comment
        id: pr_review_comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = github.context.payload;
            if (payload.comment && payload.comment.body.includes('/in-review')) {
              core.setFailed('Merge is disabled because of /in-review comment.');
            }
            console.log('No /in-review comment found. Merge is allowed.');
