name: Prevent PR merge with '리뷰중' in comment

on:
  pull_request:
    branches:
      - feature/**
    types: [opened, synchronize]

jobs:
  prevent-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check PR body '리뷰중'
        run: |
          body=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .body)

          if [[ $body == *"리뷰중"* ]]; then
            echo "PR body contains '리뷰중'. Blocking merge."
            exit 1
          fi

          echo "PR body does not contain '리뷰중'. Proceeding with merge."
          exit 0
        shell: bash

      - name: Prevent workflow from running on future comment edits
        run: |
          if [[ "${{ github.event.action }}" == "synchronize" ]]; then
            echo "PR has been synchronized. Exiting workflow."
            exit 0
          fi
