name: Pull request comment

on:
  pull_request:
    branches:
      - main
  issue_comment:
    types: [created, edited, deleted]

jobs:
  pull_request_comment:
    if: contains(github.event.comment.html_url, '/pull/') # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check In Review
        if: contains(github.event.comment.body, '/in-review') # check the comment if it contains the keywords
        run: exit 1
      - name: Check Approve
        if: "!contains(github.event.comment.body , '/in-review')"
        run: exit 0
